services:
  # samba:
  #   build: ./samba
  master:
    dns:
      - 100.100.100.100
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    command:
      - master
      - -ip=bobo01
      - -ip.bind=0.0.0.0
      - -peers=lina01:9333,nix01:9333,bobo01:9333
  volume:
    dns:
      - 100.100.100.100
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    command:
      - volume
      - -mserver=lina01:9333,nix01:9333,bobo01:9333
      - -ip.bind=0.0.0.0
      - -ip=bobo01
      - -port=8080
    depends_on:
      - master
  filer:
    dns:
      - 100.100.100.100
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    command:
      - filer
      - -master=lina01:9333,nix01:9333,bobo01:9333
      - -ip=bobo01
      - -ip.bind=0.0.0.0
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs
    ports:
      - 8333:8333
      - 9327:9327
    command:
      - s3
      - -filer=filer:8888
      - -ip.bind=0.0.0.0
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
    command:
    - webdav
    - -filer=filer:8888
    depends_on:
      - master
      - volume
      - filer