services:
  # master:
  #   restart: always
  #   dns:
  #     - 100.100.100.100
  #   image: chrislusf/seaweedfs
  #   ports:
  #     - 9333:9333
  #     - 19333:19333
  #   command:
  #     - master
  #     - -ip=lina01
  #     - -ip.bind=0.0.0.0
  #     - -peers=lina01:9333,nix01:9333,bobo01:9333
  #     - -defaultReplication=111
  volume:
    restart: always
    dns:
      - 100.100.100.100
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    command:
      - volume
      - -mserver=nix02:9333,nix01:9333,bobo01:9333
      - -ip.bind=0.0.0.0
      - -ip=lina01
      - -port=8080
      - -dataCenter=h1
      - -rack=lina
    depends_on:
      - master
  filer:
    restart: always
    dns:
      - 100.100.100.100
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    command:
      - filer
      - -master=nix02:9333,nix01:9333,bobo01:9333
      - -ip=lina01
      - -ip.bind=0.0.0.0
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    restart: always
    image: chrislusf/seaweedfs
    ports:
      - 8333:8333
      - 9327:9327
    command:
      - s3
      - -filer=filer:8888
      - -ip.bind=0.0.0.0
    depends_on:
      - master
      - volume
      - filer
  webdav:
    restart: always
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
    command:
      - webdav
      - -filer=filer:8888
    depends_on:
      - master
      - volume
      - filer
  pgadmin:
    restart: always
    dns:
      - 100.100.100.100
    image: dpage/pgadmin4
    ports:
      - 5080:80
      - 5433:433
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin@1345
