default:
	@just --list

docker host="nix02" cmd="ps":
    DOCKER_HOST="ssh://root@{{host}}" docker {{cmd}}

compose host="nix02" cmd="ps" :
    DOCKER_HOST="ssh://root@{{host}}" docker-compose -f {{host}}/compose.yml {{cmd}}

deploy host="nix02":
    DOCKER_HOST="ssh://root@{{host}}" docker-compose -f {{host}}/compose.yml up -d --remove-orphans --build

dev host="nix02":
    DOCKER_HOST="ssh://root@{{host}}" docker-compose -f {{host}}/compose.yml up --build --watch --remove-orphans