#!/usr/bin/env sh
":"; exec emacs -nw -Q --load "$0" -- "$HOME/dotfiles.org" "$@" # -*- mode: emacs-lisp; lexical-binding: t; -*-

(message "hello: %s" argv)

;; Packages
(eval-and-compile
  (require 'package))

(add-to-list 'package-archives
	     '("gnu" . "http://elpa.gnu.org/packages/"))
(add-to-list 'package-archives
	     '("org" . "https://orgmode.org/elpa/"))
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))

(setq package-enable-at-startup nil)
(package-initialize)

(setq inhibit-startup-message t)

(unless (package-installed-p 'use-package)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install 'use-package))

(eval-and-compile
  (require 'use-package))

(use-package org
  :ensure org-contrib
  :pin org
  :mode (("\\.org$" . org-mode))
  :config
  (progn
    (require 'org-tempo)
    (setq org-log-done 'time)
    (setq org-confirm-babel-evaluate nil)
    (setq org-html-validation-link nil)
    ))

(use-package evil
  :ensure t
  :config
  (progn
    (evil-mode t) ;; globally enable evil mode
    (setq evil-default-cursor t) ;; follow this settings
    ;; https://gist.github.com/gariepyalex/cfaf6fbe631b5e818096
    (setq evil-respect-visual-line-mode t) ;; respect visual lines
    (setq evil-search-module 'isearch) ;; use emacs' built-in search functionality.
    (setq evil-want-C-u-scroll t) ;; allow scroll up with 'C-u'
    (setq evil-want-C-d-scroll t) ;; allow scroll up with 'C-d'
    (setq evil-want-integration t) ;; necessary for evil collection
    (setq evil-want-keybinding nil)
    (setq evil-split-window-below t) ;; split window created below
    (setq evil-vsplit-window-right t) ;; vertically split windows created to the righto
    (setq evil-want-C-i-jump nil) ;; hopefully this will fix weird tab behaviour
    (setq evil-undo-system 'undo-redo) ;; undo via 'u', and redo the undone change vis 'C-r'
    (evil-set-initial-state 'message-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal)
    ;; buffers in which I want to immediately start typing should be in 'insert' state by default.
    (evil-set-initial-state 'eshell-mode 'insert)
    (evil-set-initial-state 'magit-diff-mode 'insert)
    ))
