apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
  labels:
    name: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        args:
        - "--token"
        - >-
          eyJhIjoiNTBlZTZkZjg5MWFiODMzNTI0MDAwYTAzNTgxMzQ2MjkiLCJ0IjoiMmUwMTM2OWMtMmE4ZC00Yzk0LThkY2MtMmQ1MTRjZmQwZDQ4IiwicyI6Ik0ySmlOV0pqTjJZdE56a3haQzAwWm1ZMUxUZ3lZalV0WkdZNFlUSTBNR1UxWVRVNSJ9
        command:
        - cloudflared
        - tunnel
        - "--protocol"
        - http2
        - "--metrics"
        - 0.0.0.0:2000
        - run
        image: cloudflare/cloudflared:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 2000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
